// src/components/header.vue
<template >
  <header class="sticky top-0 h-16 text-center">
    <nav class="flex justify-between mx-10 h-full text-center  align-middle items-center">
      <div>
        <a href="#" class="text-gray-800 hover:bg-gray-50 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg border text-sm px-4 lg:px-5 py-2 lg:py-2.5 mr-2  focus:outline-none">ورود</a>
      </div>
      <div class="flex justify-around gap-16">
        <a href="#">تماس با ما</a>
        <a href="#">درباه ما </a>
        <a href="#">خانه</a>
      </div>
    </nav>
  </header>
</template>

<script setup>
</script>

// src/components/Header/Header.jsx
import React from 'react'
import './Header.css'



const Header = () => {
  return (
    <div className="header py-2 ">

      <div className="header-container container">
        <div className="header-right-side">
          <ul className="nav d-flex align-center justify-between">
            <li><a href="#" > خانه </a></li>
            <li><a href="#" > درباره ما </a></li>
            <li><a href="#" > تماس با ما </a></li>
          </ul>
        </div>
        <div className="header-left-side">
          <div className="logo h1 "> LOGO </div>
        </div>
      </div>


    </div>
  )
}

export default Header
